// demo/svelte/src/App.svelte
<script>
	import Paper, { Title, Content } from "@smui/paper";
	import Textfield from "@smui/textfield";
	import { DiacriticRemover } from '@marketto/diacritic-remover';

	const diacriticRemover = new DiacriticRemover();

	const text = {
		_diacriticText: '',
		_cleanText: ' ',
		get diacritic() {
			return this._diacriticText;
		},
		set diacritic(value) {
			this._diacriticText = value;
			this._cleanText = diacriticRemover.replace(value);
		},
		get clean() {
			return this._cleanText || ' ';
		},
		set clean(value) {}
	};
</script>

<main>
	<img
		class="svelte-logo"
		src="https://raw.githubusercontent.com/sveltejs/svelte/29052aba7d0b78316d3a52aef1d7ddd54fe6ca84/site/static/images/svelte-android-chrome-512.png"
		alt="Svelte logo"	
	/>
	<Paper>
		<Title>Diacritic Remover</Title>
		<Content class="content">
			<Textfield
				class="text-input text-diacritic"
				variant="outlined"
				label="Type here text with accents/diacritics"
				bind:value={text.diacritic}
			></Textfield>
			<Textfield
				class="text-input text-clean"
				variant="outlined"
				label="Diacritic-free Text"
				bind:value={text.clean}
				readonly
			></Textfield>
		</Content>
	</Paper>
</main>

<style lang="scss">
	main {
		text-align: center;
		display: flex;
		flex-direction: column;
		padding: 2em;
		width: 80vw;
		max-width: 36em;
		margin: auto;

		.svelte-logo {
			max-width: 12em;
			margin: auto;
		}
	}
	:global(.content) {
		display: flex;
		flex-direction: column;
	}
	:global(.text-input) {
		margin: 2em 1em;
	}
	:global([readonly]) {
		pointer-events: none;
		border-color: blue;
	}
</style>

// demo/vue/src/App.vue
<template>
  <v-app>
    <v-content>
      <v-container
        class="fill-height"
        fluid
      >
        <v-row
          align="center"
          justify="center"
        >
          <v-col
            cols="12"
            align="center"
          >
            <img alt="vue-logo" src="./assets/logo.png">
          </v-col>
          <v-col
            cols="12"
            sm="8"
            md="4"
          >
            <v-card class="elevation-12">
              <v-toolbar
                color="secpmdary"
                dark
                flat
              >
                <v-toolbar-title>Diacritic Remover</v-toolbar-title>
                <v-spacer />
              </v-toolbar>
              <v-card-text>
                <v-form>
                  <v-text-field
                    label="Diacritic Text"
                    name="diacriticText"
                    v-model="diacriticText"
                    placeholder="Type here text with accents/diacritics"
                    outlined
                  />

                  <v-text-field
                    label="Diacritic-free Text"
                    name="cleanText"
                    v-model="cleanText"
                    placeholder=" "
                    outlined
                    readonly
                  />
                </v-form>
              </v-card-text>
            </v-card>
          </v-col>
        </v-row>
      </v-container>
    </v-content>
  </v-app>
</template>

<script>
  import DiacriticRemover from '@marketto/diacritic-remover';
  const diacriticRemover = new DiacriticRemover();

  export default {
    data: () => ({
      diacriticText: "",
      get cleanText() {
        return diacriticRemover.replace(this.diacriticText);
      }
    }),
  }
</script>
<style lang="sass">

</style>
