// demo/vue/src/App.vue
<template>
  <v-app>
    <v-content>
      <v-container
        class="fill-height"
        fluid
      >
        <v-row
          align="center"
          justify="center"
        >
          <v-col
            cols="12"
            sm="8"
            md="4"
          >
            <v-card class="elevation-12">
              <v-toolbar
                color="secpmdary"
                dark
                flat
              >
                <v-toolbar-title>Diacritic Remover</v-toolbar-title>
                <v-spacer />
              </v-toolbar>
              <v-card-text>
                <v-form>
                  <v-text-field
                    label="Diacritic Text"
                    name="diacriticText"
                    v-model="diacriticText"
                    placeholder="Type here text with accents/diacritics"
                    outlined
                  />

                  <v-text-field
                    label="Diacritic-free Text"
                    name="cleanText"
                    v-model="cleanText"
                    placeholder=" "
                    outlined
                    readonly
                  />
                </v-form>
              </v-card-text>
            </v-card>
          </v-col>
        </v-row>
      </v-container>
    </v-content>
  </v-app>
</template>

<script>
  import DiacriticRemover from '@marketto/diacritic-remover';
  const LATIN_DICT = require('@marketto/diacritic-remover/dictionaries/latin.json');
  const i18n_global = require('@marketto/diacritic-remover/dictionaries/i18n/global.json');
  const diacriticRemover = new DiacriticRemover(LATIN_DICT, i18n_global);

  export default {
    data: () => ({
      diacriticText: "",
      get cleanText() {
        return diacriticRemover.replace(this.diacriticText);
      }
    }),
  }
</script>

// demo/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import DiacriticRemover from '@marketto/diacritic-remover';
const LATIN_DICT = require('@marketto/diacritic-remover/dictionaries/latin.json');
const i18nGlobal = require('@marketto/diacritic-remover/dictionaries/i18n/global.json');
const diacriticRemover = new DiacriticRemover(LATIN_DICT, i18nGlobal);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  public diacriticText = '';
  public get cleanText(): string {
    return diacriticRemover.replace(this.diacriticText) || ' ';
  }
}

<div class="container">
  <img
    class="logo"
    alt="Angular Logo"
    src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
  />
  <mat-card>
    <mat-card-header>
      <mat-card-title>Diacritic Remover</mat-card-title>
    </mat-card-header>
    <mat-card-content>
        <mat-form-field appearance="outline">
          <mat-label>Diacritic Text</mat-label>
          <input
            matInput
            name="diacriticText"
            placeholder="Type here text with accents/diacritics"
            [(ngModel)]="diacriticText"
          >
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Diacritic-free Text</mat-label>
          <input
            matInput
            name="cleanText"
            [ngModel]="cleanText"
            readonly
          >
        </mat-form-field>
    </mat-card-content>
  </mat-card>
</div>
